//export const serverAddress = 'http://localhost:4000/'
//export const serverAddress = 'http://192.168.31.39:4000/'
//export const serverAddress = 'https://abctnfssc.herokuapp.com/'
export const serverAddress = 'https://flipraitnfssc.azurewebsites.net/'
export const registerAddress = serverAddress + 'register'
export const loginAddress = serverAddress + 'login'
export const forgotpassAddress = serverAddress + 'forgotpassword'
export const checkToken = serverAddress + 'loginwithtoken'
export const logoutAddress = serverAddress + 'logout'

export const getPersonalBoards = serverAddress + 'personalboards'
export const getLists = serverAddress + 'lists'
export const getCards = serverAddress + 'cards'

export const getTeams = serverAddress + 'teams'
export const createTeamAddress = serverAddress + 'createteam'
